name: Build pandas wheel

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: alpine:3.14.3

    steps:
      - name: Install dependencies
        run: |
          apk update
          apk add --no-cache \
            git \
            python3 \
            py3-pip \
            python3-dev \
            build-base \
            linux-headers \
            openblas-dev \
            gfortran

      - name: Clone repository
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://x-access-token:${TOKEN}@github.com/${{ github.repository }} repo
          cd repo
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Build wheel
        run: |
          cd repo
          python3 -m pip install -U pip setuptools wheel cython meson ninja
          mkdir -p wheelhouse
          pip wheel pandas==2.3.3 -w wheelhouse

      - name: Commit and Push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd repo

          git add wheelhouse

          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi

          git commit -m "Add pandas 2.3.3 wheel"
          git push origin HEAD