name: Build and Commit pandas wheel

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: alpine:3.20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          apk add --no-cache \
            python3 \
            py3-pip \
            python3-dev \
            build-base \
            openblas-dev \
            gfortran \
            linux-headers

      - name: Upgrade pip tools
        run: |
          python3 -m pip install -U pip wheel setuptools

      - name: Build pandas wheel
        run: |
          mkdir -p wheelhouse
          pip wheel pandas==2.3.3 -w wheelhouse

      - name: Commit wheel to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add wheelhouse
          git commit -m "Add pandas 2.3.3 wheel" || echo "No changes"
          git push